apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        version: v1
    spec:
      containers:
      - name: demo
        image: akihikokuroda/demo1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000